name: deploy

on:
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
          cache: npm

      - run: npm ci

      - run: npm install -g @aws-amplify/cli

      - uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::186890147549:role/tryamplify-dev-deploy
          aws-region: ap-northeast-1

      - run: aws sts get-caller-identity

      - run: amplify pull --yes

      - run: amplify status
